# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_test.ipynb.

# %% auto 0
__all__ = ['say_hello', 'test_hello_world']

# %% ../nbs/01_test.ipynb 2
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/01_test.ipynb 5
def test_hello_world(): 
    "Outputs 'hello world'"
    return "hello world"
